version: '3.7'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
        - ./db/db:/data/db
        - ./db/configdb:/data/configdb
    env_file:
      - .env
  app:
    build:
      context: .
      network: host
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./data:/data
    depends_on:
      - db


