version: '3.7'

services:
  db:
    image: mongo
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    network_mode: host
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    network_mode: host
    depends_on:
      - db